image: Visual Studio 2017

install:
  - set PROJECT_DIR=Desktop/Fallturm
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - choco install -y InnoSetup
  - set PATH=%PATH%;%QTDIR%\bin;"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\Hostx64\x64";"C:\Program Files (x86)\Inno Setup 5"
  - cmd: echo %PATH%
build_script:
  - cd Desktop/Fallturm
  - qmake Fallturm.pro
  - nmake
after_build:
  - windeployqt release/Fallturm.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - cmd: cp lib/* release/
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Desktop/Fallturm/setup/setup.exe
  - path: Desktop/Fallturm/release
    type: zip

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Fallturm-Software Release'
  provider: GitHub
  auth_token:
    secure: dQVcTF6DiR2PNMN669wx9hUaz0/5gqIpE56zDXOW94KFmz2oFn9Qbd9ApmsQ6Wn9 
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true