image: Visual Studio 2017

install:
  - set PROJECT_DIR=Desktop/Fallturm
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - choco install -y InnoSetup
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set PATH=%QTDIR%\bin;"C:\Program Files (x86)\Inno Setup 5";%PATH%
  - cmd: echo %PATH%
build_script:
  - cd Desktop/Fallturm
  - qmake Fallturm.pro -spec win32-msvc
  - nmake
after_build:
  - windeployqt release/Fallturm.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - rm -f release/*.o
  - rm -f release/*.obj
  - rm -f release/*.cpp
  - iscc innosetup.iss

artifacts:
  - path: Desktop/Fallturm/setup/setup.exe
  - path: Desktop/Fallturm/release
    type: zip

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Fallturm-Software Release'
  provider: GitHub
  auth_token:
    secure: dQVcTF6DiR2PNMN669wx9hUaz0/5gqIpE56zDXOW94KFmz2oFn9Qbd9ApmsQ6Wn9 
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true